import { LegalShell } from "@/pages/LegalShell"

export default function Terms() {
  return (
    <LegalShell title="Terms of use">
      <p style={{ marginTop: 0 }}>
        By using ChartSense, you agree to these terms. If you do not agree, do not use the service.
      </p>
      <p>
        <strong style={{ color: "var(--color-white)" }}>Educational only.</strong> Output is generated by AI
        and is for education and discussion. It is not financial, investment, or trading advice. You are solely
        responsible for your trading decisions.
      </p>
      <p>
        <strong style={{ color: "var(--color-white)" }}>No warranty.</strong> The service is provided “as
        is.” We do not warrant accuracy, completeness, or fitness for any purpose. AI can be wrong or
        misleading.
      </p>
      <p>
        <strong style={{ color: "var(--color-white)" }}>Acceptable use.</strong> Do not use the service for
        unlawful activity, to harass others, or to attempt to overload or compromise our systems.
      </p>
      <p>
        <strong style={{ color: "var(--color-white)" }}>Changes.</strong> We may change or discontinue the
        service or these terms; continued use after changes constitutes acceptance where allowed by law.
      </p>
      <p style={{ marginBottom: 0, fontSize: 13 }}>
        Operator reference: Bar Book LLC (as noted in the app footer). Last updated: March 2026.
      </p>
    </LegalShell>
  )
}
